"""Generate supplementary NVDA labels for Unicode's 128 box-drawing symbols.

Existing NVDA/CLDR entries (arrows, math, emoji, punctuation) are not duplicated.
Names derive from Python's Unicode Character Database; see UNICODE-LICENSE.txt.
German labels are project translations. Regenerate with Python 3.11 or later.
"""
from pathlib import Path
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
GERMAN = {
    "LIGHT": "dünn", "HEAVY": "dick", "HORIZONTAL": "waagerecht",
    "VERTICAL": "senkrecht", "DOWN": "unten", "UP": "oben",
    "LEFT": "links", "RIGHT": "rechts", "AND": "und",
    "DOUBLE": "doppelt", "SINGLE": "einfach", "TRIPLE": "dreifach",
    "QUADRUPLE": "vierfach", "DASH": "gestrichelt", "ARC": "gerundet",
    "DIAGONAL": "diagonal", "UPPER": "obere", "LOWER": "untere",
    "TO": "nach", "CROSS": "Kreuz",
}
# Shorter labels for the most common terminal diagrams. Mixed-weight and
# dashed forms retain the more detailed Unicode descriptions below.
COMMON = {
    0x2500: ("horizontal line", "waagerechte Linie"),
    0x2502: ("vertical line", "senkrechte Linie"),
    0x250c: ("top left corner", "Rahmenecke oben links"),
    0x2510: ("top right corner", "Rahmenecke oben rechts"),
    0x2514: ("bottom left corner", "Rahmenecke unten links"),
    0x2518: ("bottom right corner", "Rahmenecke unten rechts"),
    0x251c: ("vertical line with branch right", "senkrechte Linie mit Abzweig rechts"),
    0x2524: ("vertical line with branch left", "senkrechte Linie mit Abzweig links"),
    0x252c: ("horizontal line with branch down", "waagerechte Linie mit Abzweig unten"),
    0x2534: ("horizontal line with branch up", "waagerechte Linie mit Abzweig oben"),
    0x253c: ("line crossing", "Linienkreuzung"),
}


def content(language):
    rows = ["# Supplementary NVDA symbol definitions, generated by tools/generate_symbol_dictionary.py.",
            "# Unicode-derived labels: see UNICODE-LICENSE.txt. Project translations: MIT.",
            "# Level all: quiet at lower levels; available during character navigation.",
            "# Never preserve raw box characters: legacy engines cannot encode them.",
            "symbols:"]
    for number in range(0x2500, 0x2580):
        char = chr(number)
        words = unicodedata.name(char).removeprefix("BOX DRAWINGS ").split()
        if number in COMMON:
            label = COMMON[number][language == "de"]
        elif language == "de":
            label = "Rahmenlinie " + " ".join(GERMAN[word] for word in words)
        else:
            label = "box drawing " + " ".join(words).lower()
        rows.append(f"{char}\t{label}\tall\tnever")
    return "\n".join(rows) + "\n"


if __name__ == "__main__":
    for language in ("en", "de"):
        target = ROOT / "nvda/addon/locale" / language / "symbols-openevv.dic"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content(language), encoding="utf-8", newline="\n")
